trigger:
  batch: "true"
  branches:
    include:
    - master

variables:
- template: variables.yml

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build job
    strategy:
      matrix:
        OANApp:
          imageName: ui
        IGIApp:
          imageName: worker
    pool:
      #vmImage: ubuntu-latest
      name: KubernetesAgents  #change to your own build agent or use vmImage above
    steps:

    #below task only required for custom KubernetesAgents
    - task: DockerInstaller@0
      displayName: 'Docker Installer'
      inputs:
        dockerVersion: 17.09.0-ce
        releaseType: stable

    - template: steps.docker.yml