version: '3'
services:
  ui:
    build: ui
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  worker:
    build: worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  redis:
    image: "redis:alpine"
    ports:
      - "13378:6379"