apiVersion: v1
kind: Service
metadata:
  name: azcontoptionsui
spec:
  type: LoadBalancer
  selector:
    app: azcontoptionsui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azcontoptionsui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azcontoptionsui
  template:
    metadata:
      labels:
        app: azcontoptionsui
    spec:
      containers:
      - name: azcontoptionsui
        image: cadullacr.azurecr.io/azcontoptionsui:v0.7
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 200M
        env:
          - name: "queueConnectionString"
            value: "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=cadullq;AccountKey=[secret snipped]"
          - name: "queueName"
            value: "cadullq"
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azcontoptionsworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azcontoptionsworker
  template:
    metadata:
      labels:
        app: azcontoptionsworker
    spec:
      containers:
      - name: azcontoptionsworker
        image: cadullacr.azurecr.io/azcontoptionsworker:v0.7
        resources:
          limits:
            cpu: 50m
            memory: 200M
        env:
          - name: "queueConnectionString"
            value: "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=cadullq;AccountKey=[secret snipped]"
          - name: "queueName"
            value: "cadullq"
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: azcontoptionsworker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azcontoptionsworker
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50