apiVersion: apps/v1
kind: Deployment
metadata:
  name: azcontoptionsworkernew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azcontoptionsworkernew
  template:
    metadata:
      labels:
        app: azcontoptionsworkernew
    spec:
      containers:
      - name: azcontoptionsworkernew
        image: cadullacr.azurecr.io/azcontoptionsworker:v0.7
        resources:
          limits:
            cpu: 50m
            memory: 200M
        env:
          - name: "queueConnectionString"
            value: "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=cadullq;AccountKey=[secret snipped]"
          - name: "queueName"
            value: "cadullq"